networks:
  nginx-proxy:
    name: nginx-proxy

services:

  podverse_api:
    image: podverse/podverse_api
    container_name: podverse_api_prod
    privileged: true
    env_file:
      - ../../../config/podverse-api-prod.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 1234
    expose:
      - 1234
    ports:
      - 127.0.0.1:1234:1234
    hostname: podverse_api
    volumes:
      - ../../../config/google/jwt.keys.json:/tmp/src/config/google/jwt.keys.json
      - ../../../config/google/firebase-podverse-app-key.json:/mnt/config/google/firebase-podverse-app-key.json
    command: npm start
    networks:
      - nginx-proxy
    logging:
      driver: "syslog"
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

  podverse_web:
    image: podverse/podverse_web
    container_name: podverse_web_prod
    depends_on:
      - podverse_api
    env_file:
      - ../../../config/podverse-web-prod.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 3000
    expose:
      - 3000
    ports:
      - 127.0.0.1:3000:3000
    hostname: podverse_web
    networks:
      - nginx-proxy
    command: npm start
    logging:
      driver: "syslog"
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
