version: "3.9"

networks:
  nginx-proxy:
    name: nginx-proxy

services:

  podverse_api:
    image: podverse/podverse_api
    container_name: podverse_api_sandbox
    privileged: true
    env_file:
      - ../../../config/podverse-api-sandbox.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 1234
    expose:
      - 1234
    ports:
      - 127.0.0.1:1234:1234
    hostname: podverse_api
    command: npm start
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

  podverse_web:
    image: podverse/podverse_web
    container_name: podverse_web_sandbox
    depends_on:
      - podverse_api
    env_file:
      - ../../../config/podverse-web-sandbox.env
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 3000
    expose:
      - 3000
    ports:
      - 127.0.0.1:3000:3000
    hostname: podverse_web
    networks:
      - nginx-proxy
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
