networks:
  nginx-proxy:
    name: nginx-proxy


services:

  podverse_api_worker:
    image: podverse/podverse_api:latest
    container_name: podverse_api_worker_prod
    env_file:
      - /opt/podverse-ops/config/podverse-api-prod.env
    volumes:
      - /opt/podverse-ops/config/google/firebase-podverse-app-key.json:/mnt/config/google/firebase-podverse-app-key.json
    logging:
      driver: "syslog"
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    networks:
      - nginx-proxy
