networks:
  nginx-proxy:
    name: nginx-proxy

services:

  podverse_db:
    image: postgres:16.2-bookworm
    container_name: podverse_db_sandbox
    env_file:
      - ../../../config/podverse-db-sandbox.env
    ports:
      - '5432:5432'
    volumes:
      - /mnt/podverse_db_sandbox_volume:/var/lib/postgresql/data
    command: postgres -c checkpoint_completion_target=0.7 -c wal_buffers=16MB -c default_statistics_target=50 -c random_page_cost=1.1 -c effective_io_concurrency=100 -c work_mem=5242kB -c min_wal_size=512MB -c max_wal_size=1GB -c max_worker_processes=2 -c max_parallel_workers_per_gather=1 -c max_parallel_workers=2
    restart: always
    shm_size: 2gb
    logging:
      driver: "syslog"
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
